apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tf3cn3mwg-python 
  janus-idp.io/tekton: tf3cn3mwg-python
  backstage.io/kubernetes-id: tf3cn3mwg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tf3cn3mwg-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  