apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tf3cn3mwg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tf3cn3mwg-python 
  name: tf3cn3mwg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tf3cn3mwg-python 
